### ISSUE TITLE
fix: mayo risk class is always shown as high in the MAYO VS PROPKD graph

### ISSUE THREAD

**Issue by constantinwolff** [halbritter-lab/adpkd-risk#33]
### Description:
Fix the bug, that the MAYO risk class is always shown as high in the MAYO VS PROPKD graph, even if it is calculated as low and displayed as low in the MAYO AND PROPKD graph.

### Acceptance criteria: 

- the mayo risk class must also be able to be displayed as low and intermediate in the MAYO VS PROPKD graph, analogous to the risk categorization
- for the PROPKD score this already works perfectly

### Related files:

- MayoVsPROPKDChart.vue

**Comment by berntpopp** [comment]
Should be fixed now
